const commonCatalogFields = {
  name: { required: true },
  description: { nullable: true },
  is_active: { type: 'boolean' },
};

module.exports = {
  roles: {
    table: 'roles',
    fields: commonCatalogFields,
    columns: ['id', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
    searchColumns: ['name', 'description'],
    orderBy: 'name',
  },
  'domain-providers': {
    table: 'domain_providers',
    fields: {
      name: { required: true },
      website_url: { nullable: true },
      support_email: { nullable: true },
      is_active: { type: 'boolean' },
    },
    columns: ['id', 'name', 'website_url', 'support_email', 'is_active', 'created_at', 'updated_at'],
    searchColumns: ['name', 'website_url', 'support_email'],
    orderBy: 'name',
  },
  'domain-extensions': {
    table: 'domain_extensions',
    fields: {
      extension: { required: true },
      description: { nullable: true },
      is_active: { type: 'boolean' },
    },
    columns: ['id', 'extension', 'description', 'is_active', 'created_at', 'updated_at'],
    searchColumns: ['extension', 'description'],
    orderBy: 'extension',
  },
  'domain-types': {
    table: 'domain_types',
    fields: commonCatalogFields,
    columns: ['id', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
    searchColumns: ['name', 'description'],
    orderBy: 'name',
  },
  'domain-actions': {
    table: 'domain_actions',
    fields: commonCatalogFields,
    columns: ['id', 'name', 'description', 'is_active', 'created_at', 'updated_at'],
    searchColumns: ['name', 'description'],
    orderBy: 'name',
  },
  'provider-extension-prices': {
    table: 'provider_extension_prices',
    fields: {
      domain_provider_id: { required: true, type: 'number' },
      domain_extension_id: { required: true, type: 'number' },
      price_amount: { required: true },
      currency_code: { required: true },
      effective_from: { required: true },
      effective_to: { nullable: true },
      is_active: { type: 'boolean' },
    },
    columns: [
      'id',
      'domain_provider_id',
      'domain_extension_id',
      'price_amount',
      'currency_code',
      'effective_from',
      'effective_to',
      'is_active',
      'created_at',
      'updated_at',
    ],
    searchColumns: ['currency_code'],
    orderBy: 'effective_from',
    orderDirection: 'desc',
  },
  'provider-service-prices': {
    table: 'provider_service_prices',
    fields: {
      domain_provider_id: { required: true, type: 'number' },
      service_type: { required: true },
      service_name: { required: true },
      price_amount: { required: true },
      currency_code: { required: true },
      effective_from: { required: true },
      effective_to: { nullable: true },
      is_active: { type: 'boolean' },
    },
    columns: [
      'id',
      'domain_provider_id',
      'service_type',
      'service_name',
      'price_amount',
      'currency_code',
      'effective_from',
      'effective_to',
      'is_active',
      'created_at',
      'updated_at',
    ],
    searchColumns: ['service_type', 'service_name', 'currency_code'],
    orderBy: 'effective_from',
    orderDirection: 'desc',
  },
  'financial-settings': {
    table: 'financial_settings',
    fields: {
      name: { required: true },
      base_currency_code: { required: true },
      usd_exchange_rate: { required: true },
      vat_rate: { required: true },
      effective_from: { required: true },
      effective_to: { nullable: true },
      is_active: { type: 'boolean' },
    },
    columns: [
      'id',
      'name',
      'base_currency_code',
      'usd_exchange_rate',
      'vat_rate',
      'effective_from',
      'effective_to',
      'is_active',
      'created_at',
      'updated_at',
    ],
    searchColumns: ['name', 'base_currency_code'],
    orderBy: 'effective_from',
    orderDirection: 'desc',
  },
};
